-- V1_1__criar_tabela_avaliacao_livro.sql

    CREATE TABLE tb_avaliacao_livro (
        atualizada boolean,
        nota INTEGER NOT NULL,
        data_avaliacao TIMESTAMP(6) NOT NULL,
        id bigint generated BY DEFAULT AS IDENTITY,
        id_usuario uuid NOT NULL,
        comentario VARCHAR(500),
        titulo_livro VARCHAR(255) NOT NULL,
        PRIMARY KEY (id)
    );
    ALTER TABLE tb_avaliacao_livro
       ADD CONSTRAINT uk_avaliacao_usuario_livro
       UNIQUE (id_usuario, titulo_livro);