CREATE TABLE historico_leitura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    livro_id VARCHAR(255) NOT NULL,
    paginas_lidas INTEGER NOT NULL,
    data_leitura TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT historico_leitura_pkey PRIMARY KEY (id)
);